#!/bin/bash
APP="qtbrynhildr"

case $UNAME in
    CYGWIN*)
		mingw32-make clean
		# for static build
		rm -f ${APP}_plugin_import.cpp
		# delete executable file
		rm -f release/${APP}.exe debug/${APP}.exe
		# delete manual
		pushd ../doc/manual
		make clean
		popd
		rm -rf ../dist/doc/manual/*
		# delete files for install
		./install clean
		echo "Done."
		;;
	Linux)
		make clean
		# delete executable file
		rm -f ${APP}
		pushd ../doc/manual
		# delete manual
		make clean
		popd
		rm -rf ../dist/doc/manual/*
		# delete files for install
		./install clean
		echo "Done."
		;;
    *)
		echo "Not support platform."
		;;
esac

rm -f ${APP}.log
