#!/bin/bash
APP="QtBrynhildr"

case $UNAME in
	CYGWIN*)
		if [ "$1" = "" ] ; then
			mingw32-make clean
			# delete executable file
			rm -f release/${APP}.* debug/${APP}.*
			# delete executable file for Android
			rm -f lib${APP}.so
		fi
		if [ "$1" = "cygwin" ] ; then
			make clean
			# delete executable file
			rm -f ${APP}.exe
		fi
		# delete coverity scan directory
		rm -rf cov-int
		# delete manual
		pushd ../doc/manual
		make clean
		popd
		rm -rf ../dist/doc/manual/*
		# delete files for install
		./install clean
		;;
	Linux)
		make clean
		# delete executable file
		rm -f ${APP}
		pushd ../doc/manual
		# delete manual
		make clean
		popd
		rm -rf ../dist/doc/manual/*
		# delete files for install
		./install clean
		;;
	FreeBSD)
		make clean
		# delete executable file
		rm -f ${APP}
		pushd ../doc/manual
		# delete manual
		make clean
		popd
		rm -rf ../dist/doc/manual/*
		# delete files for install
		./install clean
		;;
	Darwin)
		make clean
		# delete executable file
		rm -rf ${APP}.app
		pushd ../doc/manual
		# delete manual
		make clean
		popd
		rm -rf ../dist/doc/manual/*
		# delete files for install
		./install clean
		;;
	*)
		echo "clean : Not support platform. $UNAME"
		exit 1;
		;;
esac

echo "$0 : Done."

rm -f ${APP}.log
