#!/bin/bash
UNAME=`uname`
UNAMEM=`uname -m`

source ./setup_qt5 $1

# check arg1
if [ -n "$1" ] ; then
	case $1 in
		clean)
			;;
		man)
			;;
		cygwin)
			;;
		*)
			echo "Unkown argument : $1"
			exit 1
			;;
	esac
fi

# setting
APP="qtbrynhildr"
APPNAME="QtBrynhildr"
ISS="$APP.iss"
INSTALL="/usr/bin/install"
INSTALLFLAGS="-C"
DATE=`date +%Y%m%d`

# check environment
case $UNAME in
	CYGWIN*)
		if [ -n "$1" ] ; then
			case $1 in
				cygwin)
					UNAMEM=`uname -m`
					case $UNAMEM in
						x86_64)
							DISTDIR="../dist/cygwin/cygwin_x64"
							PKGNAME="cygwin_x64"
							echo "Installing for Cygwin x64..."
							;;
						x86)
							DISTDIR="../dist/cygwin/cygwin_x86"
							PKGNAME="cygwin_x86"
							echo "Installing for Cygwin x86..."
							;;
					esac
					;;
				clean)
					# for Text
					DISTDIR="../dist/windows"
					;;
			esac
		else
			DISTDIR="../dist/windows"
		fi
		;;
	Linux)
		UNAMEM=`uname -m`
		case $UNAMEM in
			x86_64)
				DISTDIR="../dist/linux/linux_x64"
				PKGNAME="linux_x64"
				echo "Installing for Linux x64..."
				;;
			i686)
				DISTDIR="../dist/linux/linux_x86"
				PKGNAME="linux_x86"
				echo "Installing for Linux x86..."
				;;
		esac
		;;
	FreeBSD)
		UNAMEM=`uname -m`
		case $UNAMEM in
			amd64)
				DISTDIR="../dist/linux/freebsd_x64"
				PKGNAME="freebsd_x64"
				echo "Installing for FreeBSD x64..."
				;;
			i386)
				DISTDIR="../dist/linux/freebsd_x86"
				PKGNAME="freebsd_x86"
				echo "Installing for FreeBSD x86..."
				;;
		esac
		;;
	Darwin)
		UNAMEM=`uname -m`
		case $UNAMEM in
			x86_64)
				DISTDIR="../dist/macosx"
				PKGNAME="macosx_x64"
				echo "Installing for Darwin x64..."
				;;
		esac
		;;
	*)
		echo "$0 : Not support platform. $UNAME"
		exit 1;
		;;
esac

# clean
if [ "$1" = "clean" ] ; then
	echo "Cleaning..."
	if [ "${DISTDIR}" = "" ] ; then
		echo "DISTDIR is empty!! Please check!"
		exit 1;
	fi
	case $UNAME in
		CYGWIN*)
			# clean
			\rm -rf ${DISTDIR}/bin
			\rm -rf ${DISTDIR}/${ISS}
			;;
		Linux)
			# clean
			\rm -rf ${DISTDIR}/bin
			\rm -rf ${DISTDIR}/doc
			;;
		Darwin)
			# clean
			\rm -rf ${DISTDIR}/*
			;;
		*)
			echo "$0 : Not support platform."
			exit 1;
			;;
	esac

	echo "$0 : Done."
	exit 0;
fi

# man
if [ "$1" = "man" ] ; then
	echo "Installing manual..."
	case $UNAME in
		CYGWIN*)
			# copy manual file
			pushd ../doc/manual
			make html
			make install
			popd
			exit 0;
			;;
		Linux)
			# copy manual file
			pushd ../doc/manual
			make html
			make install
			popd
			exit 0;
			;;
		FreeBSD)
			# copy manual file
			pushd ../doc/manual
			make html
			make install
			popd
			exit 0;
			;;
		Darwin)
			# copy manual file
			pushd ../doc/manual
			make html
			make install
			popd
			exit 0;
			;;
		*)
			echo "$0 : Not support platform."
			exit 1;
			;;
	esac

	echo "$0 : Done."
	exit 0;
fi

# install
case $UNAME in
	CYGWIN*)
		# check
		if [ "$1" = "" ] ; then
			echo "Installing for windows..."
			if [ ! -x release/${APP}.exe ] ; then
				echo "NOT Found ${APP}.exe"
				exit 1;
			fi
			VERSION=`release/${APP}.exe -vv`
			# make package string
			PKGSTRING="${APP}-windows-v${VERSION}-${DATE}.exe"
			# for windows
			# create directory
			mkdir -p ${DISTDIR}/bin
			echo "copy DLL files..."
			# for Qt DLL
			mkdir -p ${DISTDIR}/bin/platforms
			mkdir -p ${DISTDIR}/bin/imageformats
			mkdir -p ${DISTDIR}/bin/audio
			${INSTALL} ${INSTALLFLAGS} ${QTROOT}/bin/Qt5Core.dll ${DISTDIR}/bin
			${INSTALL} ${INSTALLFLAGS} ${QTROOT}/bin/Qt5Gui.dll ${DISTDIR}/bin
			${INSTALL} ${INSTALLFLAGS} ${QTROOT}/bin/Qt5Multimedia.dll ${DISTDIR}/bin
			${INSTALL} ${INSTALLFLAGS} ${QTROOT}/bin/Qt5Network.dll ${DISTDIR}/bin
			${INSTALL} ${INSTALLFLAGS} ${QTROOT}/bin/Qt5Widgets.dll ${DISTDIR}/bin
			${INSTALL} ${INSTALLFLAGS} ${QTROOT}/bin/libgcc_s_dw2-1.dll ${DISTDIR}/bin
			${INSTALL} ${INSTALLFLAGS} ${QTROOT}/bin/libstdc++-6.dll ${DISTDIR}/bin
			${INSTALL} ${INSTALLFLAGS} ${QTROOT}/bin/libwinpthread-1.dll ${DISTDIR}/bin
			${INSTALL} ${INSTALLFLAGS} ${QTROOT}/plugins/platforms/qwindows.dll ${DISTDIR}/bin/platforms
			${INSTALL} ${INSTALLFLAGS} ${QTROOT}/plugins/imageformats/qjpeg.dll ${DISTDIR}/bin/imageformats
			${INSTALL} ${INSTALLFLAGS} ${QTROOT}/plugins/audio/qtaudio_windows.dll ${DISTDIR}/bin/audio
			# copy executable file
			echo "copy executable file..."
			${INSTALL} ${INSTALLFLAGS} release/${APP}.exe ${DISTDIR}/bin
			# copy manual file
			pushd ../doc/manual
			make html
			make install
			popd
			# create .iss
			echo "create .iss file"
			pushd ../dist
			cd windows
			find bin -type f -print | sed -f ../script/iss.sed | awk -f ../script/iss_bin.awk > tmp_bin.iss
			cd ..
			find doc/manual -type f -print | grep -v git | sed -f script/iss.sed | awk -f script/iss.awk > tmp.iss
			cat windows/${ISS}.template windows/tmp_bin.iss tmp.iss > windows/${ISS}
			rm -f windows/tmp_bin.iss tmp.iss
			popd
		fi
		if [ "$1" = "cygwin" ] ; then
			# check
			echo "Installing for cygwin..."
			if [ ! -x ./${APP} ] ; then
				echo "NOT Found ${APP}"
				exit 1;
			fi
			VERSION=`${APP} -vv`
			# for cygwin
			# create directory
			mkdir -p ${DISTDIR}/bin
			mkdir -p ${DISTDIR}/doc/manual
			# copy executable file
			echo "copy executable file..."
			${INSTALL} ${INSTALLFLAGS} ${APP} ${DISTDIR}/bin
			# copy document file
			${INSTALL} ${INSTALLFLAGS} ../dist/doc/ReadMe.txt ${DISTDIR}/doc
			${INSTALL} ${INSTALLFLAGS} ../dist/doc/LICENSE.txt ${DISTDIR}/doc
			# copy manual file
			pushd ../doc/manual
			make html
			make install
			popd
			cp -r ../dist/doc/manual/* ${DISTDIR}/doc/manual
			rm ${DISTDIR}/doc/manual/.gitkeep
			# make package string
			#PKGSTRING="${APP}-${PKGNAME}-v${VERSION}-${DATE}"
			PKGSTRING="${APP}-${PKGNAME}-v${VERSION}"
			(cd ../dist/cygwin; tar cvfj ${PKGSTRING}.tar.bz2 ${PKGNAME})
		fi
		;;
	Linux)
		# check
		echo "Installing for linux..."
		if [ ! -x ./${APP} ] ; then
			echo "NOT Found ${APP}"
			exit 1;
		fi
		VERSION=`${APP} -vv`
		# for linux
		# create directory
		mkdir -p ${DISTDIR}/bin
		mkdir -p ${DISTDIR}/doc/manual
		# copy executable file
		echo "copy executable file..."
		${INSTALL} ${INSTALLFLAGS} ${APP} ${DISTDIR}/bin
		# copy document file
		${INSTALL} ${INSTALLFLAGS} ../dist/doc/ReadMe.txt ${DISTDIR}/doc
		${INSTALL} ${INSTALLFLAGS} ../dist/doc/LICENSE.txt ${DISTDIR}/doc
		# copy manual file
		pushd ../doc/manual
		make html
		make install
		popd
		cp -r ../dist/doc/manual/* ${DISTDIR}/doc/manual
		rm ${DISTDIR}/doc/manual/.gitkeep
		# make package string
		#PKGSTRING="${APP}-${PKGNAME}-v${VERSION}-${DATE}"
		PKGSTRING="${APP}-${PKGNAME}-v${VERSION}"
#		(cd ../dist/linux; tar cvfJ ${PKGSTRING}.tar.xz ${PKGNAME})
		(cd ../dist/linux; zip -r -9 ${PKGSTRING}_tmp.zip ${PKGNAME}; cat /usr/bin/unzipsfx ${PKGSTRING}_tmp.zip > ${PKGSTRING}.run; zip -A ${PKGSTRING}.run; \rm ${PKGSTRING}_tmp.zip)
		;;
	FreeBSD)
		# check
		echo "Installing for freebsd..."
		if [ ! -x ./${APP} ] ; then
			echo "NOT Found ${APP}"
			exit 1;
		fi
		VERSION=`${APP} -vv`
		# for freebsd
		# create directory
		mkdir -p ${DISTDIR}/bin
		mkdir -p ${DISTDIR}/doc/manual
		# copy executable file
		echo "copy executable file..."
		${INSTALL} ${INSTALLFLAGS} ${APP} ${DISTDIR}/bin
		# copy document file
		${INSTALL} ${INSTALLFLAGS} ../dist/doc/ReadMe.txt ${DISTDIR}/doc
		${INSTALL} ${INSTALLFLAGS} ../dist/doc/LICENSE.txt ${DISTDIR}/doc
		# copy manual file
		pushd ../doc/manual
		make html
		make install
		popd
		cp -r ../dist/doc/manual/* ${DISTDIR}/doc/manual
		rm ${DISTDIR}/doc/manual/.gitkeep
		# make package string
		#PKGSTRING="${APP}-${PKGNAME}-v${VERSION}-${DATE}"
		PKGSTRING="${APP}-${PKGNAME}-v${VERSION}"
		(cd ../dist/freebsd; tar cvfJ ${PKGSTRING}.tar.xz ${PKGNAME})
#		(cd ../dist/freebsd; zip -r -9 ${PKGSTRING}_tmp.zip ${PKGNAME}; cat /usr/bin/unzipsfx ${PKGSTRING}_tmp.zip > ${PKGSTRING}.run; zip -A ${PKGSTRING}.run; \rm ${PKGSTRING}_tmp.zip)
		;;
	Darwin)
		echo "Installing for Darwin..."
		if [ ! -x ./${APP}.app ] ; then
			echo "NOT Found ${APP}.app"
			exit 1;
		fi
		VERSION=`${APP}.app/Contents/MacOS/${APP} -vv`
		# make package string
		#PKGSTRING="${APP}-${PKGNAME}-v${VERSION}-${DATE}"
		PKGSTRING="${APP}-${PKGNAME}-v${VERSION}"
		# for darwin
		# create directory
		mkdir -p ${DISTDIR}
		# rename to APPNAME
		mv ${APP}.app ${APPNAME}.app
		# make dmg
		${QTROOT}/bin/macdeployqt ${APPNAME}.app -dmg
		# rename to APP
		mv ${APPNAME}.app ${APP}.app
		# mv dist directory
		mv ${APPNAME}.dmg ${DISTDIR}/${PKGSTRING}.dmg
		;;
	*)
		echo "$0 : Not support platform. $UNAME"
		exit 1;
		;;
esac
echo "$0 : Done."
