#!/bin/bash
UNAME=`uname`
UNAMEM=`uname -m`
PRO="qtbrynhildr.pro"
TARGET=$1
BUILDARCH=mingw81-x64

# TARGET
if [ -n "$TARGET" ] ; then
	# BUILDARCH
	if [ -n "$2" ] ; then
		BUILDARCH=$2
	else
		echo "Usage : $0 <TARGET> <BUILDARCH>"
		exit 1;
	fi
else
case $UNAME in
	CYGWIN*)
			case $UNAMEM in
			x86_64)
				;;
			i686)
				;;
			*)
				echo "$0 : Not Support $UNAMEM"
				return;;
			esac
		;;
	Linux)
		case $UNAMEM in
			x86_64)
				BUILDARCH=linux-x64
				;;
			i686)
				BUILDARCH=linux-x86
				;;
			*)
				echo "$0 : Not Support $UNAMEM"
				return;;
		esac
		;;
	FreeBSD)
		case $UNAMEM in
			amd64)
				BUILDARCH=freebsd-x64
				;;
			i386)
				BUILDARCH=freebsd-x86
				;;
			*)
				echo "$0 : Not Support $UNAMEM"
				return;;
		esac
		;;
	Darwin)
		case $UNAMEM in
			x86_64)
				BUILDARCH=macos-x64
				;;
			*)
				echo "$0 : Not Support $UNAMEM"
				return;;
		esac
		;;
	*)
		echo "$0 : Not support platform."
		exit 1;
		;;
esac
fi

source ./setup_qt5 $TARGET

./clean $TARGET
rm -f Makefile Makefile.Release Makefile.Debug
rm -f object_script.*
echo RUN : ${QTROOT}/bin/${QMAKE} ${PRO}
${QTROOT}/bin/${QMAKE} ${PRO} BUILDARCH=${BUILDARCH}

case $UNAME in
	CYGWIN*)
		chmod 644 Makefile
		if [ -e Makefile.Release ]; then
			chmod 644 Makefile.Release
		fi
		if [ -e Makefile.Debug ]; then
			chmod 644 Makefile.Debug
		fi
		;;
	Linux)
		;;
	FreeBSD)
		;;
	Darwin)
		;;
	*)
		echo "$0 : Not support platform."
		exit 1;
		;;
esac
echo "$0 : Done."
