#!/bin/bash
UNAME=`uname`
UNAMEM=`uname -m`
PRO="qtbrynhildr.pro"

source ./setup_qt5 $1

./clean
rm -f Makefile Makefile.Release Makefile.Debug
${QTROOT}/bin/qmake ${PRO}

case $UNAME in
	CYGWIN*)
		chmod 644 Makefile
		if [ -e Makefile.Release ]; then
			chmod 644 Makefile.Release
		fi
		if [ -e Makefile.Debug ]; then
			chmod 644 Makefile.Debug
		fi
		echo "Done."
		;;
	Linux)
		echo "Done."
		;;
	Darwin)
		echo "Done."
		;;
    *)
		echo "Not support platform."
		;;
esac
