#!/bin/bash
UNAME=`uname`
UNAMEM=`uname -m`
PRO="qtbrynhildr.pro"
TARGET=$1
# Qt5.15.2
#BUILDARCH=mingw81-x64
# Qt6.4.1
BUILDARCH=mingw112-x64
# CONFIG
#CONFIG=portable

# TARGET
if [ -n "$TARGET" ] ; then
	# BUILDARCH
	if [ -n "$2" ] ; then
		BUILDARCH=$2
	else
		echo "Usage : $0 <TARGET> <BUILDARCH>"
		exit 1;
	fi
else
# BUILDARCH
case $UNAME in
	CYGWIN*)
		if [ -n "$2" ] ; then
			BUILDARCH=$2
		fi
		case $UNAMEM in
			x86_64)
				;;
			i686)
				;;
			*)
				echo "$0 : Not Support $UNAMEM"
				return;;
			esac
		;;
	Linux)
		case $UNAMEM in
			x86_64)
				BUILDARCH=linux-x64
				;;
			i686)
				BUILDARCH=linux-x86
				;;
			armv7l)
				# Raspberry Pi 3
				BUILDARCH=linux-armv7l
				;;
			*)
				echo "$0 : Not Support $UNAMEM"
				return;;
		esac
		;;
	FreeBSD)
		case $UNAMEM in
			amd64)
				BUILDARCH=freebsd-x64
				;;
			i386)
				BUILDARCH=freebsd-x86
				;;
			*)
				echo "$0 : Not Support $UNAMEM"
				return;;
		esac
		;;
	Darwin)
		case $UNAMEM in
			x86_64)
				BUILDARCH=macos-x64
				;;
			*)
				echo "$0 : Not Support $UNAMEM"
				return;;
		esac
		;;
	*)
		echo "$0 : Not support platform."
		exit 1;
		;;
esac
fi

source ./setup_qt6 $TARGET

./clean $TARGET
rm -f Makefile Makefile.Release Makefile.Debug
rm -f object_script.*
if [ -z $CONFIG ] ; then
	echo "RUN : ${QTROOT}/bin/${QMAKE} ${PRO} BUILDARCH=${BUILDARCH}"
	${QTROOT}/bin/${QMAKE} ${PRO} BUILDARCH=${BUILDARCH}
else
	echo "RUN : ${QTROOT}/bin/${QMAKE} ${PRO} BUILDARCH=${BUILDARCH} CONFIG+=$CONFIG"
	${QTROOT}/bin/${QMAKE} ${PRO} BUILDARCH=${BUILDARCH} CONFIG+=$CONFIG
fi

case $UNAME in
	CYGWIN*)
		chmod 644 Makefile
		if [ -e Makefile.Release ]; then
			chmod 644 Makefile.Release
		fi
		if [ -e Makefile.Debug ]; then
			chmod 644 Makefile.Debug
		fi
		;;
	Linux)
		;;
	FreeBSD)
		;;
	Darwin)
		;;
	*)
		echo "$0 : Not support platform."
		exit 1;
		;;
esac
echo "$0 : Done."
